using RequestMaster.Databases.MainDatabase;
using RequestMaster.Patterns;
using System.Windows;
using System.Windows.Controls;

namespace RequestMaster.Tabs
{
    public partial class Profile : UserControl 
    {
        RequestsContext db;
        ProfileMenuLogger logger;
        public Profile()
        {
            InitializeComponent();
            logger = new ProfileMenuLogger();
            db = DatabaseSingleton.CreateInstance();
            refreshTab();
            createdRequestsDataGrid.AutoGeneratedColumns += createdRequestsDataGrid_AutoGeneratedColumns;
        }

        private void createdRequestsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
        {
            createdRequestsDataGrid.Columns[0].Header = "ID";
            createdRequestsDataGrid.Columns[1].Header = "описание";
            createdRequestsDataGrid.Columns[2].Header = "номер";
            createdRequestsDataGrid.Columns[3].Header = "статус";
            createdRequestsDataGrid.Columns[4].Visibility = Visibility.Hidden;
            createdRequestsDataGrid.Columns[5].Visibility = Visibility.Hidden;
            createdRequestsDataGrid.Columns[6].Visibility = Visibility.Hidden;
            createdRequestsDataGrid.Columns[7].Visibility = Visibility.Hidden;
        }

        private void logOutButton_Click(object sender, RoutedEventArgs e)
        {
            Properties.Settings.Default.login = string.Empty;
            Properties.Settings.Default.password = string.Empty;
            Properties.Settings.Default.Save();
            AuthWindow authWindow = new AuthWindow();
            authWindow.Show();
            MainWindow.authWindowOpened = true;
            Window.GetWindow(this).Close();
        }

        private void refreshTab()
        {
            textBlockLogin.Text = $"{AuthWindow.user!.Login}";
            textBlockPassword.Text = $"{AuthWindow.user.Password}";
            textBlockEmail.Text = $"{AuthWindow.user.Email}";
            textBlockHowManyRequestsCreated.Text = $"{db.Requests.Where(x => x.WhoCreatedID == AuthWindow.user.UserID).Count()}";
            textBlockHowManyRequestsClosed.Text = $"{db.Requests.Where(x => x.WhoClosedID == AuthWindow.user.UserID).Count()}";
            createdRequestsDataGrid.ItemsSource = db.Requests.Where(x => x.WhoCreatedID == AuthWindow.user!.UserID).ToList();
            logger.log($"вкладка обновлена");
        }
    }
}