using RequestMaster.Databases.MainDatabase;
using RequestMaster.Patterns;
using System.Windows;
using System.Windows.Controls;

namespace RequestMaster.Tabs
{
    public partial class Profile : UserControl 
    {
        RequestsContext db;
        public Profile()
        {
            db = DatabaseSingleton.CreateInstance();
            InitializeComponent();
            refreshTab();
            createdRequestsDataGrid.AutoGeneratedColumns += createdRequestsDataGrid_AutoGeneratedColumns;
        }

        private void createdRequestsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
        {
            createdRequestsDataGrid.Columns[0].Header = "ID";
            createdRequestsDataGrid.Columns[1].Header = "описание";
            createdRequestsDataGrid.Columns[2].Header = "номер";
            createdRequestsDataGrid.Columns[3].Header = "статус";
            createdRequestsDataGrid.Columns[4].Visibility = Visibility.Hidden;
            createdRequestsDataGrid.Columns[5].Visibility = Visibility.Hidden;
            createdRequestsDataGrid.Columns[6].Visibility = Visibility.Hidden;
        }

        private void refreshButton_Click(object sender, RoutedEventArgs e)
        {
            refreshTab();
        }

        private void refreshTab()
        {
            textBlockLogin.Text = $"{AuthWindow.login}";
            textBlockPassword.Text = $"{AuthWindow.password}";
            textBlockEmail.Text = $"{AuthWindow.email}";
            createdRequestsDataGrid.ItemsSource = db.Requests.Where(x => x.WhoCreatedID == 1).ToList();
            App.log($"профиль: вкладка обновлена");
        }
    }
}