using RequestMaster.Databases.MainDatabase;
using RequestMaster.Exceptions;
using RequestMaster.Patterns;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace RequestMaster.Tabs
{
    public partial class Requests : UserControl
    {
        RequestsContext db;
        Request? requestCard;

        #region requestsDataGrid

        public Requests()
        {
            db = DatabaseSingleton.CreateInstance();
            InitializeComponent();
            helpButton.Focus();
            requestsDataGrid.ItemsSource = db.Requests.ToList();
            requestsDataGrid.AutoGeneratedColumns += requestsDataGrid_AutoGeneratedColumns;
        }

        private void requestsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
        {
            requestsDataGrid.Columns[0].Header = "ID";
            requestsDataGrid.Columns[1].Header = "описание";
            requestsDataGrid.Columns[2].Header = "номер";
            requestsDataGrid.Columns[3].Header = "статус";
            requestsDataGrid.Columns[4].Visibility = Visibility.Hidden;
            requestsDataGrid.Columns[5].Visibility = Visibility.Hidden;
        }
        
        #region ButtonClick
        private void SortButton_Click(object sender, RoutedEventArgs e)
        {
            if (radioButtonStatus_NotImportant.IsChecked == false)
            {
                string status = "";
                if (radioButtonStatus_Active.IsChecked == true) status = "активный";
                else if (radioButtonStatus_Processing.IsChecked == true) status = "в обработке";
                else if (radioButtonStatus_Closed.IsChecked == true) status = "закрыта";

                requestsDataGrid.ItemsSource = db.Requests.Where(x => x.Status == status.ToString()).ToList();
            }
            else
            {
                requestsDataGrid.ItemsSource = db.Requests.ToList();
            }
            CollectionViewSource.GetDefaultView(requestsDataGrid.ItemsSource).Refresh();
            App.logWriter.WriteLine($"меню заявок: заявки отсортированы\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
        }

        private void helpButton_Click(object sender, RoutedEventArgs e)
        {
            snackBar.MessageQueue?.Enqueue
                    ("нажмите на любую заявку дважды", null, null, null, false, true, TimeSpan.FromSeconds(3));
            App.logWriter.WriteLine($"меню заявок: нажата кнопка помощь\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
        }
        private void ClearFiltersButton_Click(object sender, RoutedEventArgs e)
        {
            refreshDataGridWithoutFilters();
            App.logWriter.WriteLine($"меню заявок: фильтры очищены\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
        }
        private void createRequestButton_Click(object sender, RoutedEventArgs e)
        {
            requestsDataGrid.Visibility = Visibility.Hidden;
            createRequestBorder.Visibility = Visibility.Visible;
            App.logWriter.WriteLine($"меню заявок: нажата кнопка создать заявку\t\t\t\t{(DateTime.Now).ToLongTimeString()}");

        }

        #endregion

        private void refreshDataGridWithoutFilters()
        {
            requestsDataGrid.ItemsSource = db.Requests.ToList();
            App.logWriter.WriteLine($"меня заявок: таблица обновлена без фильтров\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
        }

        #endregion

        #region createRequestBorder

        private bool isFieldsCorrect()
        {
            if (textBoxDescription.Text != "" &&
           textBoxTelephoneNumber.Text != "") return true;

            else return false;
        }

        private void clearFields()
        {
            textBoxDescription.Clear();
            textBoxTelephoneNumber.Clear();
            App.logWriter.WriteLine($"меню создания заявки: поля очищены\t\t\t\t{(DateTime.Now).ToLongTimeString()}");

        }

        public void createRequestButton2_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                RequestCreatingExceptions.checkDescription(textBoxDescription);
                RequestCreatingExceptions.checkTelephoneNumber(textBoxTelephoneNumber);

                using (RequestsContext db = new RequestsContext())
                {
                    int id = db.Requests.Count() + 1;
                    if (isFieldsCorrect())
                    {
                        Request request = new Request();
                        request.Description = textBoxDescription.Text;
                        request.TelephoneNumber = textBoxTelephoneNumber.Text;
                        request.Status = "активный";
                        request.whoCreatedID = AuthWindow.userID;
                        db.Requests.Add(request);
                        db.SaveChanges();
                        clearFields();
                        refreshDataGridWithoutFilters();
                        snackBar2.MessageQueue?.Enqueue
                            ("заявка создана", null, null, null, false, true, TimeSpan.FromSeconds(3));
                        App.logWriter!.WriteLine($"меню создания заявки: заявка №{id} создана\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
                    }

                    else
                    {
                        snackBar.MessageQueue?.Enqueue
                            ("проверьте правильность ввода данных", null, null, null, false, true, TimeSpan.FromSeconds(3));
                    }
                }
            }
            catch (Microsoft.EntityFrameworkCore.DbUpdateException)
            {
                snackBar.MessageQueue?.Enqueue
                        ("ошибка при добавлении данных", null, null, null, false, true, TimeSpan.FromSeconds(3));
            }
        }
        private void returnButton_Click(object sender, RoutedEventArgs e)
        {
            requestsDataGrid.Visibility = Visibility.Visible;
            createRequestBorder.Visibility = Visibility.Hidden;
            App.logWriter!.WriteLine($"меню создания заявки: нажата кнопка назад\t\t\t\t{(DateTime.Now).ToLongTimeString()}");
        }

        #endregion


        #region requestDetails

        private void requestsDataGrid_MouseDoubleClick(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            requestsDataGrid.Visibility = Visibility.Hidden;
            requestDetails.Visibility = Visibility.Visible;
            requestCard = db.Requests.Where(x => x.RequestID == requestsDataGrid.SelectedIndex + 1).FirstOrDefault()!;
            requestIdTextBlock.Text = $"{requestCard.RequestID}";
            requestTelephoneNumberTextBlock.Text = $"{requestCard.TelephoneNumber}";
            requestDescriptionTextBlock.Text = $"{requestCard.Description}";
            requestStatusTextBlock.Text = $"{requestCard.Status}";
        }

        private void returnButton2_Click(object sender, RoutedEventArgs e)
        {
            requestsDataGrid.Visibility = Visibility.Visible;
            requestDetails.Visibility = Visibility.Hidden;
            refreshDataGridWithoutFilters();
        }
        private void сloseRequestButton_Click(object sender, RoutedEventArgs e)
        {
            if (requestCard != null)
            {
                requestCard.Status = "закрыта";
                requestStatusTextBlock.Text = "закрыта";
                db.SaveChanges();
            }
            else
            {
                //snackBar3.MessageQueue?.Enqueue
                    //("проверьте правильность ввода данных", null, null, null, false, true, TimeSpan.FromSeconds(3));
            }
        }

        #endregion


    }
}