using RequestMaster.Databases.MainDatabase;
using RequestMaster.Other;
using RequestMaster.Patterns;
using System.Windows;
using System.Windows.Controls;

namespace RequestMaster.Tabs.RequestsTabMVVM.Models
{
    public partial class RequestDetails : UserControl
    {
        RequestsContext db;
        RequestDetailsMenuLogger logger;
        Snackbar snackBar;
        public RequestDetails()
        {
            InitializeComponent();
            snackBar = new Snackbar(snackBarXAML);
            logger = new RequestDetailsMenuLogger();
            db = DatabaseSingleton.CreateInstance();
            if (Requests.requestCard != null)
            {
                commentsDataGrid.ItemsSource = db.Comments.Where(x => x.RequestID == Requests.requestCard!.RequestID).ToList();
                commentsDataGrid.AutoGeneratedColumns += CommentsDataGrid_AutoGeneratedColumns;
                if (Requests.requestCard.Status == "активна" ||
                    Requests.requestCard.Status == "в обработке")
                {
                    closeRequestButton.Visibility = Visibility.Visible;
                    openRequestButton.Visibility = Visibility.Hidden;
                }
                else 
                {
                    closeRequestButton.Visibility = Visibility.Hidden;
                    openRequestButton.Visibility = Visibility.Visible;
                }
            }
        }

        private void CommentsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
        {
            commentsDataGrid.Columns[0].Header = "ID";
            commentsDataGrid.Columns[1].Header = "содержание";
            commentsDataGrid.Columns[2].Header = "кто создал";
            commentsDataGrid.Columns[3].Header = "дата создания";
            commentsDataGrid.Columns[4].Visibility = Visibility.Hidden;
            commentsDataGrid.Columns[5].Visibility = Visibility.Hidden;
        }
        private void addCommentButton_Click(object sender, RoutedEventArgs e)
        {
            commentsDataGrid.Visibility = Visibility.Hidden;
            addCommentButton.Visibility = Visibility.Hidden;
            newCommentGrid.Visibility = Visibility.Visible;
            returnButton2.Visibility = Visibility.Visible;

            logger.log($"нажата кнопка добавить комментарий");
        }
        private void confirmAddingCommentButton_Click(object sender, RoutedEventArgs e)
        {
            if (Requests.requestCard != null)
            {
                Comment comment = new Comment();
                comment.Content = commentTextBox.Text;
                comment.WhoCreated = AuthWindow.login!;
                comment.DateTimeOfCreating = $"{DateTime.Now:G}";
                comment.RequestID = Requests.requestCard.RequestID;

                if (Requests.requestCard.Status == "активна") 
                {
                    Requests.requestCard.Status = "в обработке";
                    requestStatusTextBlock.Text = Requests.requestCard.Status;
                }
                commentTextBox.Clear();
                db.Comments.Add(comment);
                db.SaveChanges();
                commentsDataGrid.ItemsSource = db.Comments.Where(x => x.RequestID == Requests.requestCard.RequestID).ToList();

                snackBar.show("комментарий добавлен");
                logger.log($"комментарий к заявке №{comment.RequestID} добавлен");
            }
        }

        private void returnButton_Click(object sender, RoutedEventArgs e)
        {
            Requests.requestsMenu.Visibility = Visibility.Visible;

            logger.log($"вкладка закрыта");
        }
        private void returnButton2_Click(object sender, RoutedEventArgs e)
        {
            commentsDataGrid.Visibility = Visibility.Visible;
            addCommentButton.Visibility = Visibility.Visible;
            newCommentGrid.Visibility = Visibility.Hidden;
            returnButton2.Visibility = Visibility.Hidden;

            logger.log($"меню добавления комментария закрыто");
        }
        private void сloseRequestButton_Click(object sender, RoutedEventArgs e)
        {
            closeRequestButton.Visibility = Visibility.Hidden;
            openRequestButton.Visibility = Visibility.Visible;
            Requests.requestCard.Status = "закрыта";
            Requests.requestCard.WhoClosedID = AuthWindow.user!.UserID;
            requestStatusTextBlock.Text = "закрыта";
            db.SaveChanges();

            snackBar.show("заявка закрыта");
            logger.log($"заявка №{Requests.requestCard.RequestID} закрыта");
        }

        private void openRequestButton_Click(object sender, RoutedEventArgs e)
        {
            closeRequestButton.Visibility = Visibility.Visible;
            openRequestButton.Visibility = Visibility.Hidden;
            Requests.requestCard.Status = "в обработке";
            Requests.requestCard.WhoOpenedID = AuthWindow.user!.UserID;
            requestStatusTextBlock.Text = "в обработке";
            db.SaveChanges();

            snackBar.show("заявка открыта");
            logger.log($"заявка №{Requests.requestCard.RequestID} открыта");
        }
    }
}
